config/routes.rb
Rails.application.routes.draw do
  get 'stock_watchlists/create'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :stocks, only: %i[index] do
    resources :watchlists, only: %i[create]
    resources :stock_watchlists, only: %i[create]
    resources :user_watchlist_stocks, only: %i[create]
  end
  resources :watchlists, only: %i[create]
  resources :user_watchlist_stocks, only: [:destroy]
  resources :user_watchlists, only: [:destroy]

  resources :saved_tweets, only: [:index, :create, :destroy]
end

app/views/shared/_bookmarks.html.erb
<div class="btn-group" role="group" aria-label="Basic example" data-toggle="collapse" href="#multicollapse-2" role="button" aria-expanded="false" aria-controls="multicollapse">
  <button type="button" class="btn btn-secondary wtch"><svg class="bi bi-bookmark" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M8 12l5 3V3a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v12l5-3zm-4 1.234l4-2.4 4 2.4V3a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v10.234z"/>
    </svg>Bookmarks</button>
  <button type="button" class="btn btn-secondary"></button>
</div>

<div id="accordion">
<ul class="list-group">
    <div class="scrollbar scrollbar-primary collapse multi-collapse" id="multicollapse-2">
      <div class="force-overflow">
        <% @saved_tweets.each do |tweet| %>
          <li class="list-group-item d-flex align-items-center justify-content-between">
            <button type="button" class="bookmark-btn" data-toggle="modal" data-target="#exampleModal-<%= tweet.tweet.id %>">
              <%= tweet.tweet.author %>
            </button>
            <%= link_to saved_tweet_path(tweet, query: params[:query]), method: :delete do %>
              <i class="fas fa-minus-circle delete-icon-green"></i>
            <% end %>
          </li>
        <% end %>
      </div>
    </div>
  </ul>
</div>

<!-- Modal -->


<!-- Modal -->
<% @saved_tweets.each do |tweet| %>
  <div class="modal fade" id="exampleModal-<%= tweet.tweet.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content transparent-background">

          <!-- Twitter-card -->
          <div class="d-flex card-grey-border">
            <div class="flex-grow-1">
              <div class="d-flex pl-4 py-2 card-header-element">
                <img src="<%= tweet.tweet.avatar %>" width="100%" class="avatar-large" alt="avatar-large">
                <div class="d-flex align-items-center flex-grow-1"><h3 class="mb-0 mx-3"><%= tweet.tweet.author %></h3></div>
                <div class="d-flex align-items-center mr-4"><p class="mb-0">
                  <span><%= number_to_human( tweet.tweet.follower, :format => '%n%u', :precision => 2, :units => { :thousand => 'K', :million => 'M', :billion => 'B' }) %></span> followers</p>
                    <button type="button" class="close card-close-button" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
              </div>
              <div class="pl-4 d-flex">
                <p class="flex-grow-1 pt-4 pb-3 m-0 text-grey-bottom-border text-left"><%= tweet.tweet.content %></p>
                <i class="fas fa-bookmark m-3 ml-5 bookmark-icon-green" style="font-size: 35px"></i>
              </div>
              <div class="d-flex pl-4 pb-2 pt-2">
                <i class="far fa-clock mr-3 size-clock-icon"></i>
                <p class="m-0 p-0">Created <%= time_ago_in_words(tweet.tweet.publish) %> ago</p>
              </div>
            </div>
          </div>

      </div>
    </div>
  </div>
<% end %>

app/views/shared/_figures.html.erb
<% high_instance = @quotes.order("low DESC").limit(1).first %>
<% low_instance = @quotes.order("low ASC").limit(1).first %>
<% high = @quotes.order("low DESC").limit(1).first.low / 100.0 %>
<% low = @quotes.order("low ASC").limit(1).first.low / 100.0 %>
<% start_price = @quotes.order("time_stamp ASC").limit(1).first.low / 100.0 %>
<% end_price =  @quotes.order("time_stamp DESC").limit(1).first.low / 100.0 %>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col"><%= @quotes.first.stock.name %> - key figures</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">Highest</th>
      <td><%= high.round(2) %>$</td>
    </tr>
    <tr>
      <th scope="row">Lowest</th>
      <td><%= low.round(2) %>$</td>
    </tr>
    <tr>
      <th scope="row">Start</th>
      <td><%= start_price.round(2) %>$</td>
    </tr>
    <tr>
      <th scope="row">End</th>
      <td><%= end_price.round(2) %>$</td>
    </tr>

    <% if low_instance.time_stamp > high_instance.time_stamp %>
      <tr>
        <th scope="row">Change from high to low</th>
        <td><%= (low - high).round(2) %>$</td>
      </tr>
      <tr>
        <th scope="row">Change from high to low (%)</th>
        <td><%= ((low / high) * 100.0 - 100.0).round(2) %>%</td>
      </tr>
    <% else %>
      <tr>
        <th scope="row">Change from low to high</th>
        <td><%= (high - low).round(2) %>$</td>
      </tr>
      <tr>
        <th scope="row">Change from low to high (%)</th>
        <td><%= ((high / low) * 100.0 - 100.0).round(2) %>%</td>
      </tr>
    <% end %>
    <tr>
      <th scope="row">Change over time</th>
      <td><%= (end_price - start_price).round(2) %>$</td>
    </tr>
    <tr>
      <th scope="row">Change over time (%)</th>
      <td><%= ((end_price / start_price) * 100.0 - 100.0).round(2) %> %</td>
    </tr>
  </tbody>
</table>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_future.html.erb
<h1>Partial for future</h1>

app/views/shared/_graph.html.erb
<% labels = [] %>
<% quotes_low = [] %>
<% stock_name = @quotes.first.stock.name %>

<% @quotes.each do |q| %>
  <% labels << q.time_stamp %>
  <% quotes_low << q.low / 100.0 %>
<% end %>

<% hodie = Time.new %>

<% 4.times do %>
  <% quotes_low << nil %>
<% end %>

<% d_counter = 1 %>

<% 4.times do %>
  <% labels << hodie + 86400 * d_counter %>
  <% d_counter = d_counter + 1 %>
<% end %>


<canvas id="lineChart" data-time="<%= labels.to_json %>" data-quotes="<%= quotes_low.to_json %>" data-stockname="<%= stock_name.to_json %>" aria-label="Hello ARIA World" role="img"></canvas>
<%= javascript_pack_tag 'graph' %>

app/views/shared/_info.html.erb
<% if !@quotes.first.stock.country.nil? %>
  <h2><%= link_to @quotes.first.stock.name, @quotes.first.stock.weburl, target: :_blank %></a></h2>
  <%= image_tag @quotes.first.stock.logo if !@quotes.first.stock.logo.nil? %>

  <table class="table table-striped">
    <tbody>
      <tr>
        <th scope="row">Company name</th>
        <td><%= @quotes.first.stock.company_name %></td>
      </tr>
      <tr>
        <th scope="row">Country</th>
        <td><%= @quotes.first.stock.country %></td>
      </tr>
      <tr>
        <th scope="row">Industry</th>
        <td><%= @quotes.first.stock.industry %></td>
      </tr>
      <tr>
        <th scope="row">Currency</th>
        <td><%= @quotes.first.stock.currency %></td>
      </tr>
      <tr>
        <th scope="row">Exchange</th>
        <td><%= @quotes.first.stock.exchange %></td>
      </tr>
      <tr>
        <th scope="row">IPO</th>
        <td><%= @quotes.first.stock.ipo %></td>
      </tr>
      <tr>
        <th scope="row">Market Capitalization</th>
        <td><%=  @quotes.first.stock.marketCapitalization %> $</td>
      </tr>
      <tr>
        <th scope="row">Share Outstanding</th>
        <td><%= @quotes.first.stock.shareOutstanding %></td>
      </tr>
      <tr>
        <th scope="row">Phone</th>
        <td><%= @quotes.first.stock.phone %></td>
      </tr>
    </tbody>
  </table>

<% else %>
  <h2>We're sorry but there are no infos available at the moment</h2>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_news.html.erb
<h1>Partial for news tweets</h1>

app/views/shared/_period-bar.html.erb
<% coucou = Time.new %>
<% start = @quotes.first.time_stamp %>
<% chart_end = @quotes.last.time_stamp %>


<div id="timebar">

  <div id="time-indications">
    <div>
      Selected period:
    </div>

    <div id="dates-display">
          <div class="d">from <%= start.strftime("%e %b %Y %H:%M%p") %></div>
      <div class="d">to <%= chart_end.strftime("%e %b %Y %H:%M%p") %></div>
    </div>
  </div>

  <div id="clickable-options">
      <div class=" <%= @resolution == 'M' ? 'resolution-active' : '' %> t-option"><%= link_to "monthly", controller: "stocks", action: "index", query: @quotes.first.stock.name, resolution: "M" %></div>
      <div class=" <%= @resolution == 'W' ? 'resolution-active' : '' %> t-option"><%= link_to "weekly", controller: "stocks", action: "index", query: @quotes.first.stock.name, resolution: "W" %></div>
      <div class=" <%= @resolution == 'D' ? 'resolution-active' : '' %> t-option"><%= link_to "daily", controller: "stocks", action: "index", query: @quotes.first.stock.name, resolution: "D" %></div>
      <div class=" <%= @resolution == '60' ? 'resolution-active' : '' %> t-option"><%= link_to "hourly", controller: "stocks", action: "index", query: @quotes.first.stock.name, resolution: "60" %></div>
      <div class=" <%= @resolution == '30' ? 'resolution-active' : '' %> t-option"><%= link_to "30 min", controller: "stocks", action: "index", query: @quotes.first.stock.name, resolution: "30" %></div>
      <div class=" <%= @resolution == '15' ? 'resolution-active' : '' %> t-option"><%= link_to "15 min", controller: "stocks", action: "index", query: @quotes.first.stock.name, resolution: "15" %></div>
      <div class=" <%= @resolution == '1' ? 'resolution-active' : '' %> t-option"><%= link_to "minute", controller: "stocks", action: "index", query: @quotes.first.stock.name, resolution: "1" %></div>
  </div>

</div>














<!--

<div id="timebar-flex-container">

  <div id="timeframe-hint">
    <div>from <%#= start[0, 16] %></div>
    <div> to <%#= chart_end[0, 16] %></div>
  </div>

  <div class=" <%#= @resolution == 'M' ? 'resolution-active' : '' %> t-option"><%#= link_to "M", controller: "stocks", action: "index", query: @quotes.first.stock.name, resolution: "M" %></div>
  <div class=" <%#= @resolution == 'W' ? 'resolution-active' : '' %> t-option"><%#= link_to "weekly", controller: "stocks", action: "index", query: @quotes.first.stock.name, resolution: "W" %></div>
  <div class=" <%#= @resolution == 'D' ? 'resolution-active' : '' %> t-option"><%#= link_to "daily", controller: "stocks", action: "index", query: @quotes.first.stock.name, resolution: "D" %></div>
  <div class=" <%#= @resolution == '60' ? 'resolution-active' : '' %> t-option"><%#= link_to "hourly", controller: "stocks", action: "index", query: @quotes.first.stock.name, resolution: "60" %></div>
  <div class=" <%#= @resolution == '30' ? 'resolution-active' : '' %> t-option"><%#= link_to "half-hourly", controller: "stocks", action: "index", query: @quotes.first.stock.name, resolution: "30" %></div>
  <div class=" <%#= @resolution == '15' ? 'resolution-active' : '' %> t-option"><%#= link_to "quarter-hourly", controller: "stocks", action: "index", query: @quotes.first.stock.name, resolution: "15" %></div>
  <div class=" <%#= @resolution == '1' ? 'resolution-active' : '' %> t-option"><%#= link_to "minute", controller: "stocks", action: "index", query: @quotes.first.stock.name, resolution: "1" %></div>
</div>

<div>
  <p>Last update of the chart: <%= coucou %></p>
</div>

-->

app/views/shared/_sidebar.html.erb
<aside class="sidebar">
  <div class="spark-logo mb-4 btn-sidebar">
    <%= link_to root_path, class: "d-flex w-100 justify-content-center align-items-center" do %>
      <%= image_tag "logo.png", width: 40, height: 40, class: "mx-2 margin-bottom: 0.0rem" %>
      <h1 class="mx-2">SparkNews</h1>
    <% end %>
  </div>
  <div class = "sidebar-height">
    <div class = "login text-left ml-4" >
      <% if !user_signed_in? %>
        <%= link_to "Login", new_user_session_path %>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <div class="d-flex w-100 my-4 justify-content-center align-items-center">
        <div class="nav-item dropdown">
          <div class="position-relative">
            <%= image_tag "avatar_riccardo.jpg" , width: 40, height: 40, crop: :thumb, gravity: :face, class: "avatar-sidebar avatar-large dropdown-toggle ", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </div>
        </div>
      </div>
      <div class="btn-sidebar d-flex w-100 my-1 flex-column align-items-center justify-content-center">
        <%#= link_to "Watchlist stocks", "#" %>
      </div>
    <% end %>
    <div class="" id="search">
      <%= simple_form_for :search, url: stocks_path, method: :get do |f| %>
        <div class="ml-4 form-group d-flex">
          <input class="ml-1 form-control string required flex-grow" type="text" name="query" id="search_query" placeholder="Enter a ticker (AAPL)" />
          <button name="button" type="submit" class="btn sidebar-searchbar-btn-flat">
            <i class="fas fa-search"></i>
          </button>
        </div>
      <% end %>
    </div>
    <div class="btn-sidebar d-flex w-100 flex-column align-items-center justify-content-center">
      <div class="my-1" style="width: 200px">
        <%= render 'shared/watchlist', user_watchlists: @user_watchlists %>
      </div>
      <div class="mt-3" style="width: 200px">
        <%= render 'shared/bookmarks' %>
      </div>
    </div>
  </div>
  <div class="d-flex w-100 flex-column align-items-center justify-content-center mt-5">
    <div class="footer-sidebar">
      <h3>Contact us</h3>
      <ul class= "list-inline">
        <li class="list-inline-item"><i class="fab fa-instagram"></i></li>
        <li class="list-inline-item"><i class="fab fa-facebook-square"></i></li>
        <li class="list-inline-item"><i class="fas fa-envelope"></i></li>
        <li class="list-inline-item"><i class="fas fa-phone-square"></i></li>
      </ul>
    </div>
  </div>
</aside>

app/views/shared/_tweets.html.erb
<h1 id="spark-tweet-header" class="mb-4"><%= @stock.name %> | <%= @stock.ticker %></h1>


<% @with_flag_posts.each do |post| %>

  <div class="d-flex my-3 card-grey-border">
    <div class="flex-grow-1">
      <div class="d-flex pl-4 py-2 card-header-element">
        <img src="<%= post[:user].profile_image_url_https %>" width="100%" class="avatar-large" alt="avatar-large">
        <div class="d-flex align-items-center flex-grow-1"><h3 class="mb-0 mx-3"><%= post[:user].name %></h3></div>
        <div class="d-flex align-items-center mr-4"><p class="mb-0"><span><%= number_to_human( post[:user].followers_count, :format => '%n%u', :precision => 2, :units => { :thousand => 'K', :million => 'M', :billion => 'B' }) %></span> followers</p></div>
      </div>
      <div class="pl-4 d-flex">
        <p class="flex-grow-1 pt-4 pb-3 m-0 text-grey-bottom-border text-left"><%= post[:text] %></p>
        <% tweet = [post[:user].name, post[:user].followers_count, post[:text], post[:created_at], post[:user].profile_image_url_https] %>
          <%= link_to saved_tweets_path(value: tweet, query: params[:query]), method: :post do %>
            <% if post[:bookmarked] %>
              <i class="fas fa-bookmark m-3 ml-5 bookmark-icon-green" style="font-size: 35px"></i>
            <% else %>
              <i class="far fa-bookmark m-3 ml-5 bookmark-icon-green" style="font-size: 35px"></i>
            <% end %>
          <% end %>
      </div>
      <div class="d-flex pl-4 pb-2 pt-2">
        <i class="far fa-clock mr-3 size-clock-icon"></i>
        <p class="m-0">Created <%= time_ago_in_words(post[:created_at]) %> ago</p>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_watchlist.html.erb
<div class="btn-group" role="group" aria-label="Basic example">
  <button type="button" class="btn btn-secondary wtch">
    <svg class="bi bi-card-checklist" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M14.5 3h-13a.5.5 0 00-.5.5v9a.5.5 0 00.5.5h13a.5.5 0 00.5-.5v-9a.5.5 0 00-.5-.5zm-13-1A1.5 1.5 0 000 3.5v9A1.5 1.5 0 001.5 14h13a1.5 1.5 0 001.5-1.5v-9A1.5 1.5 0 0014.5 2h-13z" clip-rule="evenodd"/>
      <path fill-rule="evenodd" d="M7 5.5a.5.5 0 01.5-.5h5a.5.5 0 010 1h-5a.5.5 0 01-.5-.5zm-1.496-.854a.5.5 0 010 .708l-1.5 1.5a.5.5 0 01-.708 0l-.5-.5a.5.5 0 11.708-.708l.146.147 1.146-1.147a.5.5 0 01.708 0zM7 9.5a.5.5 0 01.5-.5h5a.5.5 0 010 1h-5a.5.5 0 01-.5-.5zm-1.496-.854a.5.5 0 010 .708l-1.5 1.5a.5.5 0 01-.708 0l-.5-.5a.5.5 0 01.708-.708l.146.147 1.146-1.147a.5.5 0 01.708 0z" clip-rule="evenodd"/>
    </svg>
    <span>Watchlist</span>
  </button>
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-secondary">
    <svg class="bi bi-plus-circle" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" data-toggle="modal" data-target="#modalWatchlist" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M8 3.5a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5H4a.5.5 0 0 1 0-1h3.5V4a.5.5 0 0 1 .5-.5z"/>
      <path fill-rule="evenodd" d="M7.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0V8z"/>
      <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
    </svg>
  </button>
</div>

<!-- Modal -->
<div class="modal fade" id="modalWatchlist" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Watchlist's options</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%#= url: stock_user_watchlist_stocks_path(query: params[:query]), method: :post %>
      <div class="modal-body border-bottom">
        <p>Add <%= @quotes.first.stock.name %> to a current watchlist:</p>
        <%= simple_form_for [@stock, @user_watchlist_stock], url: stock_user_watchlist_stocks_path(@stock, query: params[:query]), method: :post do |f| %>
          <%= f.association :user_watchlist, include_blank: false, label_method: lambda{|user_watchlist| "#{user_watchlist.watchlist.name}"} %>
          <%= f.submit "Add to watchlist", class: "btn btn-secondary" %>
        <% end %>
      </div>
      <div class="modal-body">
        <p>or create a new watchlist:</p>
        <% if user_signed_in? %>
          <%= simple_form_for @watchlist, url: watchlists_path(query: params[:query]),method: :post do |w| %>
            <%= w.input :name %>
            <%= w.submit "Create watchlist", class: "btn btn-primary" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div id="accordion">
  <% user_watchlists.each do |uw| %>
    <ul class="list-group">
      <li class="list-group-item list-group-item-primary "data-toggle="collapse" href="#a<%= uw.watchlist.id %>" role="button" aria-expanded="false" aria-controls="multicollapse">
        <div class="d-flex align-items-center justify-content-between text-left">
          <span id="sub"><%= uw.watchlist.name %></span>
          <%= link_to user_watchlist_path(uw, query: params[:query]), method: :delete do %>
            <i class="fas fa-minus-circle delete-icon-green"></i>
          <% end %>
        </div>
      </li>
      <div class="scrollbar scrollbar-primary collapse multi-collapse" id="a<%= uw.watchlist.id %>">
        <div class="force-overflow">
          <% uw.user_watchlist_stocks.each do |uws| %>
            <li class="list-group-item d-flex align-items-center justify-content-between">
              <div>
                <i class="fas fa-chart-line pr-1"></i>
                <%= link_to uws.stock.name, stocks_path(query: uws.stock.ticker) %>
              </div>
              <%= link_to user_watchlist_stock_path(uws, query: params[:query]), method: :delete do %>
                <i class="fas fa-minus-circle delete-icon-green"></i>
              <% end %>
            </li>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
</div>



<!--
<ul class="list-group">
=======
<#% user_watchlists.each do |uw| %>
  <ul class="list-group">
>>>>>>> master
    <li class="list-group-item list-group-item-primary">
      <svg class="bi bi-card-checklist" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M14.5 3h-13a.5.5 0 00-.5.5v9a.5.5 0 00.5.5h13a.5.5 0 00.5-.5v-9a.5.5 0 00-.5-.5zm-13-1A1.5 1.5 0 000 3.5v9A1.5 1.5 0 001.5 14h13a1.5 1.5 0 001.5-1.5v-9A1.5 1.5 0 0014.5 2h-13z" clip-rule="evenodd"/>
        <path fill-rule="evenodd" d="M7 5.5a.5.5 0 01.5-.5h5a.5.5 0 010 1h-5a.5.5 0 01-.5-.5zm-1.496-.854a.5.5 0 010 .708l-1.5 1.5a.5.5 0 01-.708 0l-.5-.5a.5.5 0 11.708-.708l.146.147 1.146-1.147a.5.5 0 01.708 0zM7 9.5a.5.5 0 01.5-.5h5a.5.5 0 010 1h-5a.5.5 0 01-.5-.5zm-1.496-.854a.5.5 0 010 .708l-1.5 1.5a.5.5 0 01-.708 0l-.5-.5a.5.5 0 01.708-.708l.146.147 1.146-1.147a.5.5 0 01.708 0z" clip-rule="evenodd"/>
      </svg>
      <span id="sub"><%#= uw.watchlist.name %> </span>
    </li>
    <div class="scrollbar scrollbar-primary">
      <div class="force-overflow">
        <%# uw.user_watchlist_stocks.each do |uws| %>
          <li class="list-group-item">
            <%#= uws.stock.name %>
          </li>
        <%# end %>
      </div>
    </div>
  </ul>
<<<<<<< HEAD


 -->
<!-- =======
<#% end %>
>>>>>>> master -->